apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbg-python
  labels:
    app: lbg-python
spec:
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  replicas: 2
  selector:
    matchLabels:
      app: lbg-python
  template:
    metadata:
      labels:
        app: lbg-python
    spec:
      containers:
        - image: gcr.io/lbg-mea-11/hamza-s3:v1
          name: lbg-python
          ports:
            - containerPort: 9000
          env:
            PORT: 9000
