apiVersion: v1
kind: Service
metadata:
  name: lbg-python
  labels: 
    app: lbg-python
spec:
  type: LoadBalancer
  selector:
    app: lbg-python
  ports:
    - port: 80
      targetPort: 9000
      nodePort: 32000
      protocol: TCP
